### ISSUE TITLE
Debloating works, some apps remain

### ISSUE THREAD

**Issue by secco-online** [thanuj10/Nokia-Debloater#7]
Hey
I really appreciate the effort you put in discovering the issue of Nokia phones!
I ran the script on my Nokia 7.1 with Android 10 and it worked. The result is visible in the screenshots below (the ones removed are with a comment: "Not installed for this user")
My question/issue is: is it only my phone/the rom of my phone that has these additional com.evenwell.* packages that were not included in the debloating?
Can you please check and if needed include them in your cool script?
Thanks
Mac
 
![Screenshot_20200216-093529](https://user-images.githubusercontent.com/46870782/74601732-8c2df400-50a1-11ea-858a-e9de6118b11a.png)
![Screenshot_20200216-093553](https://user-images.githubusercontent.com/46870782/74601734-8df7b780-50a1-11ea-8b84-e34245c11052.png)
![Screenshot_20200216-093609](https://user-images.githubusercontent.com/46870782/74601735-8e904e00-50a1-11ea-8f1f-8b4e6895e0bc.png)

**Comment by thanuj10** [comment]
I left them in because some if these apps are still required by the system and is not particular to your phone. 😄

Some like the hdr.service app is required for the HDR pureview display on your 7.1. 

Bokeh Editor is there to edit the bokeh effect of portrait mode photos after you've taken them. 

Some other apps I have not investigated them enough so I've left them for now, I may remove them in the future.

**Comment by secco-online** [comment]
Hello
Thanks a lot for the quick reply. I though so that you left them on purpose :)
Have a nice day
